//
// Created by kbisland on 12/1/19.
//

#ifndef SIMPLEPACKETCOMSEXAMPLE_UDPSIMPLEPACKETCOMS_H
#define SIMPLEPACKETCOMSEXAMPLE_UDPSIMPLEPACKETCOMS_H


class UDPSimplePacketComs {

};


#endif //SIMPLEPACKETCOMSEXAMPLE_UDPSIMPLEPACKETCOMS_H
